name: my_flutter_template

environment:
  sdk: ^3.7.0

workspace:
  # apps
  - apps/my_app
  - apps/widgetbook
  # packages
  - packages/cores/core
  - packages/cores/assets
  - packages/features/auth
  - packages/features/github_repository

dev_dependencies:
  melos: ^7.0.0-dev.8

melos:
  sdkPath: .fvm/flutter_sdk

  ide:
    intellij:
      enabled: false

  command:
    clean:
      hooks:
        post: |
          melos exec --flutter -- "flutter clean"
    version:
      branch: main
      releaseUrl: true

  scripts:
    fix:
      exec: |
        dart fix --apply lib
        dart run custom_lint --fix
      description: Fix dart files.
      packageFilters:
        dirExists: lib

    pub-get:
      exec: |
        fvm flutter pub get
      description: pub get.
      packageFilters:
        dirExists: lib

    gen:
      run: dart run build_runner build --delete-conflicting-outputs
      exec:
        concurrency: 1
      description: Generate code.
      packageFilters:
        dirExists: lib
        dependsOn: "build_runner"

    gen:assets:
      run: dart run build_runner build --delete-conflicting-outputs
      exec:
        concurrency: 1
      description: Generate code.
      packageFilters:
        dirExists: lib
        dependsOn: "build_runner"
        scope: "cores_assets"

    gen:watch:
      run: dart run build_runner watch --delete-conflicting-outputs
      exec:
        concurrency: 99
      description: Generate code in watch mode.
      packageFilters:
        dirExists: lib
        dependsOn: "build_runner"

    test:
      run: flutter test
      exec:
        failFast: true
      description: Run flutter test.
      packageFilters:
        flutter: true
        dirExists: test

    pod:ios:
      exec: |
        cd ios
        rm -f Podfile.lock
        pod install --repo-update
      description: Run pod install on iOS.
      packageFilters:
        dirExists: [lib, ios]
        fileExists: "ios/Podfile"

    package:update:
      exec: |
        fvm flutter pub upgrade
      description: Update package dependencies.
      packageFilters:
        dirExists: lib

    package:update-major:
      exec: |
        fvm flutter pub upgrade --major-versions
      description: Update package dependencies.
      packageFilters:
        dirExists: lib
