// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_my_blueprint/test/ui/auth/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_my_blueprint/data/repositories/auth/auth_repository.dart'
    as _i3;
import 'package:flutter_my_blueprint/domain/model/auth/auth_state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState login(String? githubApiToken) =>
      (super.noSuchMethod(
            Invocation.method(#login, [githubApiToken]),
            returnValue: _FakeAuthState_0(
              this,
              Invocation.method(#login, [githubApiToken]),
            ),
          )
          as _i2.AuthState);

  @override
  _i2.AuthState fetchAuthState() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAuthState, []),
            returnValue: _FakeAuthState_0(
              this,
              Invocation.method(#fetchAuthState, []),
            ),
          )
          as _i2.AuthState);
}
