name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  my_app:
    path: ../../apps/my_app
  flutter:
    sdk: flutter
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0
  cores_core: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
